import type { RelationshipWorkspace } from './relationship-os-types';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString();
const daysFromNow = (days: number) => new Date(now.getTime() + days * 86400000).toISOString();

export const demoWorkspace: RelationshipWorkspace = {
  companies: [
    {
      id: 'company-novaai',
      name: 'NovaAI',
      website: 'https://example.com/novaai',
      industry: 'AI productivity',
      stage: 'Seed',
      location: 'Singapore',
      description: 'AI workflow startup evaluating expansion into a new market.',
      potentialNeed: 'Localized launch support, founder introductions, and market validation.',
      marketRelevance: 'Strong consulting opportunity if urgency and budget are confirmed.',
      budgetEstimate: '$2,000/month retainer',
    },
    {
      id: 'company-harbor-events',
      name: 'Harbor Events',
      website: 'https://example.com/harbor-events',
      industry: 'Technology events',
      location: 'Tokyo',
      description: 'Regional technology event organizer with sponsors, side events, and international guests.',
      potentialNeed: 'Sponsor activation, side event production, and community partnerships.',
      marketRelevance: 'Useful event channel for market-entry clients.',
      budgetEstimate: '$2,000-$10,000 sponsorship or event support',
    },
    {
      id: 'company-bridgepay',
      name: 'BridgePay',
      website: 'https://example.com/bridgepay',
      industry: 'Fintech',
      location: 'Global',
      description: 'Fintech platform with a cross-border user base.',
      potentialNeed: 'Partnership campaigns, local market entry, and co-marketing.',
      marketRelevance: 'Relevant for partnership-led growth conversations.',
      budgetEstimate: '$5,000-$20,000 campaign discussion',
    },
    {
      id: 'company-unclear-saas',
      name: 'Unclear SaaS startup',
      website: 'https://example.com',
      industry: 'SaaS',
      location: 'Unknown',
      description: 'Low-signal prospect with no confirmed need.',
      potentialNeed: 'Unknown.',
      marketRelevance: 'Not qualified yet.',
      budgetEstimate: 'Unknown',
    },
  ],
  people: [
    {
      id: 'person-koki',
      name: 'Koki Tanaka',
      role: 'Founder',
      companyId: 'company-novaai',
      company: 'NovaAI',
      email: 'koki@example.com',
      location: 'Singapore',
      preferredChannel: 'Email',
      relationshipStrength: 'warm',
      howWeMet: 'Met after an AI side event. Discussed a lightweight market validation pilot.',
      lastInteractionAt: daysAgo(12),
      nextFollowUpAt: daysFromNow(0),
      tags: ['market entry', 'AI', 'warm intro'],
      potentialValue: 2000,
      notes: 'Interested but has not confirmed budget. Asked for concrete validation steps.',
    },
    {
      id: 'person-event-director',
      name: 'Example Event Director',
      role: 'Event organizer',
      companyId: 'company-harbor-events',
      company: 'Harbor Events',
      email: 'aiko@example.com',
      location: 'Tokyo',
      preferredChannel: 'Email',
      relationshipStrength: 'strong',
      howWeMet: 'Worked together on a past event.',
      lastInteractionAt: daysAgo(1),
      nextFollowUpAt: daysFromNow(0),
      tags: ['events', 'sponsorship'],
      potentialValue: 5000,
      notes: 'Asked for sponsor activation outline by Friday.',
    },
    {
      id: 'person-partnership-lead',
      name: 'Example Partnership Lead',
      role: 'Partnerships Lead',
      companyId: 'company-bridgepay',
      company: 'BridgePay',
      preferredChannel: 'LinkedIn',
      relationshipStrength: 'warm',
      howWeMet: 'Intro through a mutual founder after a conference dinner.',
      lastInteractionAt: daysAgo(5),
      nextFollowUpAt: daysFromNow(1),
      tags: ['partnership', 'co-marketing'],
      potentialValue: 12000,
      notes: 'Needs tailored campaign ideas, not a generic partnership pitch.',
    },
    {
      id: 'person-daniel',
      name: 'Daniel Kim',
      role: 'Marketing Director',
      companyId: 'company-unclear-saas',
      company: 'Unclear SaaS startup',
      preferredChannel: 'Email',
      relationshipStrength: 'weak',
      howWeMet: 'Brief event conversation. Said "send me something" but did not give a specific need.',
      lastInteractionAt: daysAgo(24),
      nextFollowUpAt: daysAgo(7),
      tags: ['weak signal', 'SaaS'],
      potentialValue: 1000,
      notes: 'Three follow-ups without a meaningful reply. Consider pausing.',
    },
  ],
  opportunities: [
    {
      id: 'opp-nova-japan-retainer',
      title: 'NovaAI market-entry pilot',
      desiredOk: 'Koki agrees to a 30-minute call about a $2,000/month market-entry pilot.',
      personId: 'person-koki',
      companyId: 'company-novaai',
      stage: 'Replied',
      estimatedValue: 2000,
      probability: 45,
      priority: 'high',
      nextAction: 'Send a focused follow-up with a 30-day validation plan and ask for a call.',
      nextActionDueAt: daysFromNow(0),
      lastInteractionAt: daysAgo(12),
      blocker: 'Budget and timing are not confirmed.',
      status: 'active',
      summary: 'Warm event relationship. Interest exists, but urgency and budget are not established.',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(2),
    },
    {
      id: 'opp-harbor-sponsorship',
      title: 'Harbor Events sponsor activation package',
      desiredOk: 'The event director approves a sponsor activation outline and shares it with two sponsor candidates.',
      personId: 'person-event-director',
      companyId: 'company-harbor-events',
      stage: 'Proposal needed',
      estimatedValue: 5000,
      probability: 65,
      priority: 'high',
      nextAction: 'Prepare a one-page sponsor activation proposal.',
      nextActionDueAt: daysFromNow(0),
      lastInteractionAt: daysAgo(1),
      blocker: 'Proposal not prepared yet.',
      status: 'active',
      summary: 'Strong relationship with a concrete ask. The risk is operational delay, not relationship quality.',
      createdAt: daysAgo(14),
      updatedAt: daysAgo(1),
    },
    {
      id: 'opp-bridgepay-partnership',
      title: 'BridgePay co-marketing collaboration',
      desiredOk: 'The partnership lead agrees to explore a campaign or co-marketing collaboration.',
      personId: 'person-partnership-lead',
      companyId: 'company-bridgepay',
      stage: 'Contacted',
      estimatedValue: 12000,
      probability: 35,
      priority: 'medium',
      nextAction: 'Send three concrete campaign ideas tailored to BridgePay.',
      nextActionDueAt: daysFromNow(1),
      lastInteractionAt: daysAgo(5),
      blocker: 'Need to show relevance quickly. Generic partnership pitch will be ignored.',
      status: 'active',
      summary: 'Warm intro with a plausible partnership fit. Needs specific campaign angles and a clear meeting ask.',
      createdAt: daysAgo(7),
      updatedAt: daysAgo(5),
    },
    {
      id: 'opp-weak-saas',
      title: 'Unclear SaaS marketing lead',
      desiredOk: 'Confirm whether Daniel has a real marketing need worth discussing.',
      personId: 'person-daniel',
      companyId: 'company-unclear-saas',
      stage: 'Contacted',
      estimatedValue: 1000,
      probability: 10,
      priority: 'low',
      nextAction: 'Send one close-the-loop message or pause.',
      nextActionDueAt: daysAgo(7),
      lastInteractionAt: daysAgo(24),
      blocker: 'Weak engagement. No budget, decision-maker, or urgency.',
      status: 'active',
      summary: 'Low-signal contact. Stop spending time unless there is new signal.',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(7),
    },
  ],
  interactions: [
    {
      id: 'int-koki-event',
      date: daysAgo(12),
      type: 'Event conversation',
      summary: 'Discussed NovaAI entering a new market. Koki asked what a lightweight validation pilot would include.',
      participantIds: ['person-koki'],
      opportunityId: 'opp-nova-japan-retainer',
      sentiment: 'positive',
      commitments: ['Send a concise validation plan.'],
      followUpItems: ['Ask whether they have budget for a paid pilot.'],
    },
    {
      id: 'int-event-director-call',
      date: daysAgo(1),
      type: 'Call',
      summary: 'The event director asked for a sponsor activation outline for event partners.',
      participantIds: ['person-event-director'],
      opportunityId: 'opp-harbor-sponsorship',
      sentiment: 'positive',
      commitments: ['Prepare one-page sponsor activation outline by Friday.'],
      followUpItems: ['Send outline and ask for feedback before sharing externally.'],
    },
    {
      id: 'int-partnership-lead-intro',
      date: daysAgo(5),
      type: 'Introduction',
      summary: 'Mutual founder introduced the partnership lead for a potential co-marketing collaboration.',
      participantIds: ['person-partnership-lead'],
      opportunityId: 'opp-bridgepay-partnership',
      sentiment: 'positive',
      commitments: ['Send a few concrete collaboration ideas.'],
      followUpItems: ['Mention specific audience fit and campaign ideas.'],
    },
    {
      id: 'int-daniel-followup',
      date: daysAgo(9),
      type: 'Email',
      summary: 'Second follow-up sent. No meaningful reply.',
      participantIds: ['person-daniel'],
      opportunityId: 'opp-weak-saas',
      sentiment: 'unclear',
      commitments: [],
      followUpItems: ['Close the loop or pause.'],
    },
  ],
  actions: [
    {
      id: 'task-koki-followup',
      title: 'Follow up with Koki about the market-entry pilot',
      dueAt: daysFromNow(0),
      personId: 'person-koki',
      companyId: 'company-novaai',
      opportunityId: 'opp-nova-japan-retainer',
      priority: 'high',
      status: 'open',
      kind: 'follow_up',
      recommendationReason: 'Warm reply, but no follow-up for 12 days. Move toward a meeting and budget discussion.',
    },
    {
      id: 'task-event-proposal',
      title: 'Prepare the sponsor activation proposal',
      dueAt: daysFromNow(0),
      personId: 'person-event-director',
      companyId: 'company-harbor-events',
      opportunityId: 'opp-harbor-sponsorship',
      priority: 'high',
      status: 'open',
      kind: 'proposal',
      recommendationReason: 'Strong relationship and clear commitment. Delay is the main risk.',
    },
    {
      id: 'task-partnership-ideas',
      title: 'Send three BridgePay collaboration ideas',
      dueAt: daysFromNow(1),
      personId: 'person-partnership-lead',
      companyId: 'company-bridgepay',
      opportunityId: 'opp-bridgepay-partnership',
      priority: 'medium',
      status: 'open',
      kind: 'draft',
      recommendationReason: 'Warm intro will cool down if the next message is generic.',
    },
    {
      id: 'task-daniel-close',
      title: 'Close or pause the weak SaaS opportunity',
      dueAt: daysAgo(7),
      personId: 'person-daniel',
      opportunityId: 'opp-weak-saas',
      priority: 'low',
      status: 'open',
      kind: 'pause',
      recommendationReason: 'Three weak follow-ups without a concrete reply. Stop spending time unless there is new signal.',
    },
  ],
  drafts: [],
};
