import type { RelationshipWorkspace } from './relationship-os-types';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString();
const daysFromNow = (days: number) => new Date(now.getTime() + days * 86400000).toISOString();

export const demoWorkspace: RelationshipWorkspace = {
  companies: [
    {
      id: 'company-kakehashi',
      name: 'Kakehashi Japan',
      website: 'https://kakehashijapan.com',
      industry: 'Online Japanese learning',
      stage: 'Early revenue',
      location: 'Japan / United States',
      description: 'Online Japanese lessons and short-term Japan learning experiences.',
      potentialNeed: 'University partnerships, student acquisition, group lessons, study-abroad referrals.',
      marketRelevance: 'Strong fit for US universities, Japan clubs, study abroad offices, and language communities.',
      budgetEstimate: '$500-$3,000/month partnership or campaign value',
    },
    {
      id: 'company-bitcoincom',
      name: 'Bitcoin.com',
      website: 'https://bitcoin.com',
      industry: 'Crypto media and wallet',
      location: 'Global',
      description: 'Crypto media, wallet, and ecosystem platform with a global audience.',
      potentialNeed: 'Japan/APAC growth, co-branded campaigns, community activations, licensing.',
      marketRelevance: 'Relevant to ALTLIER and Own The Doge outbound partnership work.',
      budgetEstimate: '$5,000-$25,000 campaign or licensing discussion',
    },
    {
      id: 'company-webx',
      name: 'WebX Conference',
      website: 'https://webx-asia.com',
      industry: 'Web3 events',
      location: 'Tokyo',
      description: 'Large Japan-based Web3 conference with sponsors, side events, and international guests.',
      potentialNeed: 'Sponsor activation, side event production, community partnerships.',
      marketRelevance: 'Useful event channel for Japan market-entry clients.',
      budgetEstimate: '$2,000-$10,000 sponsorship or event support',
    },
    {
      id: 'company-novaai',
      name: 'NovaAI',
      website: 'https://example.com/novaai',
      industry: 'AI productivity',
      stage: 'Seed',
      location: 'Singapore',
      description: 'AI workflow startup evaluating Japan expansion.',
      potentialNeed: 'Localized launch support, founder introductions, Japan GTM validation.',
      marketRelevance: 'Strong consulting opportunity if urgency and budget are confirmed.',
      budgetEstimate: '$2,000/month retainer',
    },
  ],
  people: [
    {
      id: 'person-koki',
      name: 'Koki Tanaka',
      role: 'Founder',
      companyId: 'company-novaai',
      company: 'NovaAI',
      email: 'koki@example.com',
      location: 'Singapore',
      preferredChannel: 'Email',
      relationshipStrength: 'warm',
      howWeMet: 'Met after an AI side event in Tokyo. Discussed Japan launch and community testing.',
      lastInteractionAt: daysAgo(12),
      nextFollowUpAt: daysFromNow(0),
      tags: ['Japan GTM', 'AI', 'warm intro'],
      potentialValue: 2000,
      notes: 'Interested but has not confirmed budget. Asked for concrete Japan validation steps.',
    },
    {
      id: 'person-maya',
      name: 'Maya Rodriguez',
      role: 'Partnerships Lead',
      companyId: 'company-bitcoincom',
      company: 'Bitcoin.com',
      preferredChannel: 'LinkedIn',
      relationshipStrength: 'warm',
      howWeMet: 'Intro through a mutual Web3 founder after a conference dinner.',
      lastInteractionAt: daysAgo(5),
      nextFollowUpAt: daysFromNow(1),
      tags: ['Web3', 'licensing', 'partnership'],
      potentialValue: 12000,
      notes: 'Good fit for Own The Doge and ALTLIER. Needs tailored campaign ideas, not generic licensing pitch.',
    },
    {
      id: 'person-aiko',
      name: 'Aiko Sato',
      role: 'Event organizer',
      companyId: 'company-webx',
      company: 'WebX Conference',
      email: 'aiko@example.com',
      location: 'Tokyo',
      preferredChannel: 'Telegram',
      relationshipStrength: 'strong',
      howWeMet: 'Worked together on a side event last year.',
      lastInteractionAt: daysAgo(1),
      nextFollowUpAt: daysFromNow(0),
      tags: ['events', 'Tokyo', 'sponsorship'],
      potentialValue: 5000,
      notes: 'Asked for sponsor activation outline by Friday.',
    },
    {
      id: 'person-daniel',
      name: 'Daniel Kim',
      role: 'Marketing Director',
      company: 'Unconfirmed SaaS startup',
      preferredChannel: 'Email',
      relationshipStrength: 'weak',
      howWeMet: 'Brief chat at WebX booth. Said "send me something" but did not give specific need.',
      lastInteractionAt: daysAgo(24),
      nextFollowUpAt: daysAgo(7),
      tags: ['weak signal', 'SaaS'],
      potentialValue: 1000,
      notes: 'Three follow-ups without a meaningful reply. Consider pausing.',
    },
  ],
  opportunities: [
    {
      id: 'opp-nova-japan-retainer',
      title: 'NovaAI Japan GTM retainer',
      desiredOk: 'Koki agrees to a 30-minute call about a $2,000/month Japan GTM pilot.',
      personId: 'person-koki',
      companyId: 'company-novaai',
      stage: 'Replied',
      estimatedValue: 2000,
      probability: 45,
      priority: 'high',
      nextAction: 'Send a focused follow-up with a 30-day Japan validation plan and ask for a call.',
      nextActionDueAt: daysFromNow(0),
      lastInteractionAt: daysAgo(12),
      blocker: 'Budget and timing are not confirmed.',
      status: 'active',
      summary:
        'Warm event relationship. Koki showed interest in Japan expansion, but the conversation has not established urgency or budget.',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(2),
    },
    {
      id: 'opp-webx-sponsorship',
      title: 'WebX side event sponsorship package',
      desiredOk: 'Aiko approves a sponsor activation outline and shares it with two sponsor candidates.',
      personId: 'person-aiko',
      companyId: 'company-webx',
      stage: 'Proposal needed',
      estimatedValue: 5000,
      probability: 65,
      priority: 'high',
      nextAction: 'Prepare a one-page sponsor activation proposal.',
      nextActionDueAt: daysFromNow(0),
      lastInteractionAt: daysAgo(1),
      blocker: 'Proposal not prepared yet.',
      status: 'active',
      summary: 'Strong relationship with a concrete ask. The risk is operational delay, not relationship quality.',
      createdAt: daysAgo(14),
      updatedAt: daysAgo(1),
    },
    {
      id: 'opp-bitcoincom-doge',
      title: 'Bitcoin.com x Own The Doge collaboration',
      desiredOk: 'Maya agrees to explore a campaign, loyalty, or licensing collaboration.',
      personId: 'person-maya',
      companyId: 'company-bitcoincom',
      stage: 'Contacted',
      estimatedValue: 12000,
      probability: 35,
      priority: 'medium',
      nextAction: 'Send three concrete campaign ideas tailored to Bitcoin.com.',
      nextActionDueAt: daysFromNow(1),
      lastInteractionAt: daysAgo(5),
      blocker: 'Need to show relevance quickly. Generic IP licensing pitch will be ignored.',
      status: 'active',
      summary: 'Warm intro with strong brand fit. Needs specific campaign angles and a clear next meeting ask.',
      createdAt: daysAgo(7),
      updatedAt: daysAgo(5),
    },
    {
      id: 'opp-weak-saas',
      title: 'Unclear SaaS marketing lead',
      desiredOk: 'Confirm whether Daniel has a real marketing need worth discussing.',
      personId: 'person-daniel',
      stage: 'Contacted',
      estimatedValue: 1000,
      probability: 10,
      priority: 'low',
      nextAction: 'Send one close-the-loop message or pause.',
      nextActionDueAt: daysAgo(7),
      lastInteractionAt: daysAgo(24),
      blocker: 'Weak engagement. No budget, decision-maker, or urgency.',
      status: 'active',
      summary: 'Low-signal contact. The user has already spent enough time unless Daniel responds with a specific need.',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(7),
    },
  ],
  interactions: [
    {
      id: 'int-koki-event',
      date: daysAgo(12),
      type: 'Event conversation',
      summary: 'Discussed NovaAI entering Japan. Koki asked what a lightweight market validation pilot would include.',
      participantIds: ['person-koki'],
      opportunityId: 'opp-nova-japan-retainer',
      sentiment: 'positive',
      commitments: ['Send a concise Japan validation plan.'],
      followUpItems: ['Ask whether they have budget for a paid pilot.'],
    },
    {
      id: 'int-aiko-call',
      date: daysAgo(1),
      type: 'Call',
      summary: 'Aiko asked for a sponsor activation outline for WebX side event partners.',
      participantIds: ['person-aiko'],
      opportunityId: 'opp-webx-sponsorship',
      sentiment: 'positive',
      commitments: ['Prepare one-page sponsor activation outline by Friday.'],
      followUpItems: ['Send outline and ask for feedback before sharing externally.'],
    },
    {
      id: 'int-maya-intro',
      date: daysAgo(5),
      type: 'Introduction',
      summary: 'Mutual founder introduced Maya for potential Bitcoin.com x DOGE collaboration.',
      participantIds: ['person-maya'],
      opportunityId: 'opp-bitcoincom-doge',
      sentiment: 'positive',
      commitments: ['Send a few concrete collaboration ideas.'],
      followUpItems: ['Mention ALTLIER, Own The Doge, and specific Bitcoin.com audience fit.'],
    },
    {
      id: 'int-daniel-followup',
      date: daysAgo(9),
      type: 'Email',
      summary: 'Second follow-up sent. No meaningful reply.',
      participantIds: ['person-daniel'],
      opportunityId: 'opp-weak-saas',
      sentiment: 'unclear',
      commitments: [],
      followUpItems: ['Close the loop or pause.'],
    },
  ],
  actions: [
    {
      id: 'task-koki-followup',
      title: 'Follow up with Koki about the Japan GTM pilot',
      dueAt: daysFromNow(0),
      personId: 'person-koki',
      companyId: 'company-novaai',
      opportunityId: 'opp-nova-japan-retainer',
      priority: 'high',
      status: 'open',
      kind: 'follow_up',
      recommendationReason: 'Warm reply, but no follow-up for 12 days. Move toward a meeting and budget discussion.',
    },
    {
      id: 'task-aiko-proposal',
      title: 'Prepare the sponsor activation proposal for Aiko',
      dueAt: daysFromNow(0),
      personId: 'person-aiko',
      companyId: 'company-webx',
      opportunityId: 'opp-webx-sponsorship',
      priority: 'high',
      status: 'open',
      kind: 'proposal',
      recommendationReason: 'Strong relationship and clear commitment. Delay is the main risk.',
    },
    {
      id: 'task-maya-ideas',
      title: 'Send three Bitcoin.com collaboration ideas',
      dueAt: daysFromNow(1),
      personId: 'person-maya',
      companyId: 'company-bitcoincom',
      opportunityId: 'opp-bitcoincom-doge',
      priority: 'medium',
      status: 'open',
      kind: 'draft',
      recommendationReason: 'Warm intro will cool down if the next message is generic.',
    },
    {
      id: 'task-daniel-close',
      title: 'Close or pause the weak SaaS opportunity',
      dueAt: daysAgo(7),
      personId: 'person-daniel',
      opportunityId: 'opp-weak-saas',
      priority: 'low',
      status: 'open',
      kind: 'pause',
      recommendationReason: 'Three weak follow-ups without a concrete reply. Stop spending time unless there is new signal.',
    },
  ],
  drafts: [],
};
